### ISSUE TITLE
用进程池爬取保存图片时出现创建文件路径的错误

### ISSUE THREAD

**Issue by glwjh** [Germey/Python3WebSpider#5]
Germey您好！
我是一个编程菜鸟，跟潮流选择了Python作为自己的第一门编程语言。学习您在GitHub上的教程两个多月了，非常感谢您的无私分享！
我参照您的教程写了一个爬虫来爬取网页上的图片，具体是用进程池爬取单页（chapter），再用for loop遍历每一页，main方法代码如下：
```python
def main(chapter_numbers):
    for i in range(chapter_numbers):
        url = ''
        html = get_one_page(url)
        print('Chapter ' + str(i + 1) + ': Downloading')
        pool = Pool()
        item = ([x for x in parse_one_page(html, i)])
        pool.map(save_image, item)
        pool.close()
        pool.join()
```
这其中用了您本篇教程中的`save_image`方法来保存自己爬取的图片，但是出现error：`FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'img\\1'`和`FileExistsError: [Errno 17] Cannot create a file when that file already exists: 'img\\1'`，于是查阅了os库的document对`save_image`作了如下修改：
1. `os.makedirs()`方法中加了`exist_ok`参数并设为`True`
2. 用`os.path.join()`方法拼接path
3. 用`os.path.isfile()`方法检查是否有重复文件

修改后的代码如下：
```python
def save_image(item):
    img_path = os.path.join('img' + os.path.sep + item.get('chapter'))
    if not os.path.exists(img_path):
        os.makedirs(img_path, exist_ok=True)
    try:
        resp = requests.get(item.get('image'))
        if codes.ok == resp.status_code:
            file_path = os.path.join(img_path + os.path.sep + 
                '{file_name}.{file_suffix}'.format(
                file_name=item.get('title'), 
                file_suffix='jpg'))
            if not os.path.isfile(file_path):
                with open(file_path, 'wb') as f:
                    f.write(resp.content)
                print('Downloaded image path is %s' % file_path)
            else:
                print('Already Downloaded', file_path)
    except Exception as e:
        print(e)
```
经过修改后error不再出现，但是我有几个问题如下：
- 关于我的error，我的理解是进程池运行时抓了两张图片并同时写入，所以路径“打架”了，变成`img\\1`。添加`exist_ok=True`了后，允许有同名的文件存在，就变成”覆盖“了。请问我的理解对吗？
- 进程池是如何运作的？`pool.map()`的第二个参数是不是没有先后顺序但是能保证全部被遍历过？如果是这样对于顺序不敏感的遍历用`pool.map()`方法是不是效率更高？
- 我的其余两个修改有必要吗？

我的表述可能不太专业，请谅解，先谢过Germey了！

**Comment by Germey** [comment]
* 第一个问题，是的，但也可以在写入的时候加上 exists 判断应该也不会出现问题。
* 进程池如你所说，对于顺序不敏感的完全可以用 map 来代替，且比较方便。
* 修改的判断情况还是很详细的，没有问题。也有优化地方，比如 reqeusts 的 Exception 的异常处理类型，可以写的更明确一点。有些地方可以加 exists 判断，当然用 isfile 也是可以的。
